const DEFAULT_BYPASS_DOMAINS = [
  // GitHub 相关
  'objects-origin.githubusercontent.com',
  '*.ghproxy.net',
  '*.ghp.ci',
  '*.kkgithub.com',
  '*.dgithub.xyz',
  'pages.github.com',
  'help.github.com',
  'docs.github.com',
  '*.github.blog',
  '*.githubassets.com',
  'ssh.github.com',

  // Docker 相关
  'www.docker.com',
  'login.docker.com',
  'api.dso.docker.com',
  'desktop.docker.com',
  'docs.docker.com',

  // 微软相关
  '*.s-microsoft.com',
  '*.xboxlive.com',
  '*.microsoftonline.com',
  '*.msedge.net',
  '*.microsoft.com',
  '*.windows.com',
  '*.office.com',
  '*.office.net',
  '*.msn.com',

  // 国内服务
  '*.mihoyo.com',
  '*.bilicomic.com',
  '*.bilibili.com',
  '*.bilivideo.com',
  '*.biliapi.net',
  '*.csdn.net',
  '*.so.com',
  '*.baidu.com',
  '*.baiducontent.com',
  '*.bdimg.com',
  '*.bdstatic.com',
  '*.bdydns.com',
  '*.tencent.com',
  '*.qq.com',
  '*.weixin.com',
  '*.weixinbridge.com',
  '*.wechat.com',
  '*.idqqimg.com',
  '*.gtimg.com',
  '*.qpic.com',
  '*.qlogo.com',
  '*.myapp.com',
  '*.aliyun.com',
  '*.alipay.com',
  '*.taobao.com',
  '*.ut.taobao.com',
  '*.tmall.com',
  '*.alipayobjects.com',
  '*.dingtalk.com',
  '*.mmstat.com',
  '*.alicdn.com',
  '*.hdslb.com',
  'gitee.com',
  '*.gitee.com',
  '*.gitee.io',
  '*.giteeusercontent.com',
  '*.immersivetranslate.com',
  '*.trafficmanager.net',
  '*.ximalaya.com',
  '*.xmcdn.com',
  '*.dingtalkapps.com',
  '*.aliyuncs.com',
  '*.feishu.cn',
  '*.volcengine.com',
  '*.zijieapi.com',

  // 其他服务
  '*.cmicapm.com',
  '*.cloudflare-cn.com',
  '*kaspersky*.com',
  '*.upd.kaspersky.com',
  '*.lanhuapp.com',
  '*.soboten.com',
  '*.sandboxie-plus.com',
  '*.wuyou.net',
  '*.pyecharts.org',
  '*.bcloudlink.com',
  '*.qijishow.com',
  '*.z-lib.fo',
  '*.finalshell.com',
  '*.minebbs.com',
  '*.spigotmc.org',
  '*.virustotal.com',
  '*.gitlab.com',
  '*.deepseek.com',
  '*steaminventoryhelper.com',
  '*.youdemai.com',
  '*.casualthink.com',

  // 特定 IP
  '44.239.165.12',
  '3.164.110.117',

  // 中国相关
  '*.cn',
  '*china*',
  '*.ghproxy.*',

  // DeepL
  'www.deepl.com',

  // Mozilla/Firefox
  '*.mozilla.org',
  '*.mozilla.com',
  '*.mozilla.net',
  '*.firefox.com',
  '*.firefox.org',
  '*.mozillademos.org',
  '*.mozillians.org',
  '*.mozillians.net',
  '*.mozillians.com',

  // Java 依赖
  '*.sonatype.org',
  '*.maven.org',
  '*.mvnrepository.com',

  // Apple
  '*.apple.com',
  '*.icloud.com',

  // WPS
  '*.wps.com',
  '*.wps.net',
  '*.ksord.com',

  // 360
  '*.qihoo.com',
  '*.qihucdn.com',
  '*.360.com',
  '*.360safe.com',
  '*.360buyimg.com',
  '*.360buy.com',
  '*.jd.com',
  '*.jcloud.com',
  '*.jcloudcs.com',
  '*.jcloudcache.com',
  '*.jcloudcdn.com',
  '*.jcloudlb.com',

  // 中国移动
  '*.10086.com',
  '*.10086cloud.com',
  '*.139.com',
  '*.xunlei.com',
  '*.icpapi.com',
  '*.navicat.com',

  // 本地地址
  'localhost',
  'localhost.*',
  '127.*.*.*',
  'test.*',
  '10.*.*.*',
  '172.16.*.*',
  '172.17.*.*',
  '172.18.*.*',
  '172.19.*.*',
  '172.20.*.*',
  '172.21.*.*',
  '172.22.*.*',
  '172.23.*.*',
  '172.24.*.*',
  '172.25.*.*',
  '172.26.*.*',
  '172.27.*.*',
  '172.28.*.*',
  '172.29.*.*',
  '172.30.*.*',
  '172.31.*.*',
  '192.168.*.*',
];

module.exports = { DEFAULT_BYPASS_DOMAINS };
